sudo: true
dist: trusty
language: python
cache: pip
matrix:
  fast_finish: true
  include:
  - python: 3.4
    env: TOX_ENV=py34-dj110
  - python: 3.5
    env: TOX_ENV=py35-dj110
  - python: 2.7
    env: TOX_ENV=py27-dj111
  - python: pypy
    env: TOX_ENV=pypy-dj111
  - python: 3.4
    env: TOX_ENV=py34-dj111
  - python: 3.5
    env: TOX_ENV=py35-dj111
  - python: 3.6
    env: TOX_ENV=py36-dj111
  - python: pypy3
    env: TOX_ENV=pypy3-dj111
  - python: 3.5
    env: TOX_ENV=py35-djdev
  - python: 3.6
    env: TOX_ENV=py36-djdev
  - python: 3.6
    env: TOX_ENV=flake8
  - python: 3.6
    env: TOX_ENV=isort
  - python: 3.6
    env: TOX_ENV=readme
  - python: 3.6
    env: TOX_ENV=check-manifest
  allow_failures:
  - env: TOX_ENV=py35-djdev
  - env: TOX_ENV=py36-djdev
  - env: TOX_ENV=pypy3-dj111
  - env: TOX_ENV=py27-dj111  # SQLite is too old
  - env: TOX_ENV=pypy-dj111  # SQLite is too old
addons:
  apt:
    sources:
    - travis-ci/sqlite3
    packages:
    - sqlite3
install:
- pip install -U pip setuptools tox wheel
before_script:
- sqlite3 -version
script:
- tox -e "${TOX_ENV}"
