dist: xenial
sudo: false

language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7

cache: pip

env:
  global:
  - secure: u0BkKcx3XkU+fi+Hf+Lmp+BMntW/QYme4GRrwKVQh1Blfunz6FIYxcNJDRwvrccGgj9BtUVg5O1Il7Hxo/k0OGb1glJni3G5C98qRroX5qG3jk+ptWLSYadE82CRUEB72UMKcuDq2lu+R6ACEQ/EQzLhVkX8GuFQ7/W6QRzbf6LN/OfOuz2OiZH/7WPxKk73EKQZtvslEqTI6zB0+RRjCt1ObHeZ4etYzRblO+gcVfeN1ySPeS5oyC8PwxjHMhpYMcMQLDjmqUU/ARQfDgAQVOyVKb7j/INmesWSRoBUWjkkeTiE9Wtx4MdAQ1bLnIhWOyDk5PXGDcK2SEOq2BMP0mScfqKzqUDQ2VGpVGR6ukBvkvN9OjZXR0TDx/ryrLgAG+z4pvzzN/XJbyVSGkH4tK2X8mua5kisb25OBEuMNDLRhubrHfWpTgWuYCNSPGQR2iE/LKRbDqWj5svMdbYmhBxV1/eLDga0KZo4PStyKfzJHYm/Qz7TfwgxMYV0WXofZmIi4LtX7j0LyEho62PwAPm8aiYfRFxXXtd5UFEEVZGSHXDUL5y4sILARzQmrIL4ZP9z52fxeBePpY6i8Otuov0GjtLifg0FjBGo5N7D1ANT00wKlbJCARstNtIElN/11dILdJE2y1KJeYiZI1SfoRUJk0TdJjgji5MIz6IHTQ0=
  matrix:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=master

matrix:
  fast_finish: true
  include:
  - env: TOXENV=flake8
    python: 3.7
  - env: TOXENV=isort
    python: 3.7
  - env: TOXENV=readme
    python: 3.7
  - env: TOXENV=check-manifest
    python: 3.7
  exclude:
  - python: 2.7
    env: DJANGO=2.0
  - python: 2.7
    env: DJANGO=2.1
  - python: 3.4
    env: DJANGO=2.1
  allow_failures:
  - env: DJANGO=master
  # Use old sqlite3 that does not support shared memory
  - env: DJANGO=1.11
    python: 2.7

install:
- travis_retry pip install -U pip tox-travis setuptools wheel
before_script:
- sqlite3 -version
script:
- tox
deploy:
  provider: pypi
  user: uncovertruth
  password:
    secure: vm63jxiupnzZI1A9UwiE8JOJ02/7u8sIHUdx0K4Nb9teqZew+uk4DaSSY6MXtjFtatnBocBG/9xc7Ej90suFfQzx5ouYguWvhMDnBivzSvFQ+L68PlgNQ2od09r7NidCOKMkgBDjM0wPnSjzAfaPQatc3PCHcA04BOH10+KPZdDDNQtvjiqRPcFuIZiet0yA5ZECDy4vYeZInXREikbFneKW4NH35eigtZbxxXPX1QBTP9eWPbEM9Hjy+q79/njXHSkyTvdeCjfBHj2Uqul78FVwxdZI37Q4Bl7dgnJ96ccqmHVPEkdhW2wpIcu04hvF1Yo6xVmcx6xsSK77lNh2apLJh5eaYv0jA107z0XszamUZyhMrIIXhrMeXOFOBvsc6oT+VvV7AIfJTLulmsRT49fwAPxzyjobGwqTN0vEJAtfux07WptR2e1IQvOGIzl2JMBckEB+37ecB5H50fW0F9MjxzsE99nEkM0QkKRe64UEZ45Dtgltzdg91JdDzhJMD7qJAfaUpLsBc2dXeoi9Is/QgpPJ15vA7JWmMOuV0eT0gaIHuaRHGd5SHT75jAmu3v5ygulXVIesytasoFFfICWDXP4YsPro+PNmyTd8QW+tAJkigSFt85E5fYhdTToZ4jDMGFC2+ryoxUkk84XX1Ax3Fu22QRip8XjWRRz72Uc=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: uncovertruth/django-horizon
    python: 3.7
    condition: $DJANGO = 2.1
notifications:
  email: false
  slack:
    secure: HPa3L23uNVcVnXsNtkMkIuhOEOLTqvSbcXPy3ScjHEuZrRqKhHaX6DPx2/6PXR6azyKmywoqcVxDNfAiK5ditlvefxKyp8a1Csduwd4uGEqxAgxM72F/Qjfdb+QXCVp2M6ypjy8H9GSZ8pR888Bea1Vid49c8z1JEr3FbTw/acfY4WGeZTrbD2ZEsVYSEKJR/vS7/YxEY3jO4qxRoGul056LhZvabKACM0TseQkPIDLbY+/f/21LOz1d6TRdukRV9PdOp2lN4wJSloNja3j1x3Ox/auX2U1wAekH33HWyMi3au6X0zdLrEoNhCWdkfRy22qr/JSqeq+qo8xo4bzPrrMuUYzSBtMSp16BWQj47NSJAOhyIlMvtKbRgFdHuu+4XxRpGcmg+MjFdtyzOOjXldMr95adI9+RKzWLQUvBtxJFptDW48yf2t+VIP1WnNfHHoIjj1rROyGTGTE36FrbjAi3V5oRWYBkpKMEmlcVmN/1DKoQ8GECyDKlw0R84xYWUau/LpM20THFzEnPgqUY/DG7a9aqYR/Szo0FY4NuHcW3jzBKeH0xQEOps2OeVVfr7CHcq9NK1AAFYOMeEi5LR6yMfBpbzfVKSRU5EgvmcH8Sr5pBP77UMxiersCEwK3GvwLGrioV4KY598GTGti4tcRaoc1PU+7+EmeFdsGPi4w=
